# - name: Set up conda environment
#   uses: conda-incubator/setup-miniconda@v2
#   with:
#     miniconda-version: "latest"
#     auto-update-conda: true
#     activate-environment: conda-env
#   if: runner.os == 'Windows' || runner.os == 'Linux'

# - name: Install libraries for Windows
#   run: |
#     conda install -c conda-forge boost
#   # conda install -c conda-forge eigen
#   shell: pwsh
#   if: runner.os == 'Windows'

# - name: Install libraries for Linux
#   run: |
#     conda install -c conda-forge boost
#   # conda install -c conda-forge eigen
#   # sudo apt-get update
#   # sudo apt-get install libboost-all-dev
#   shell: bash
#   if: runner.os == 'Linux'

# - uses: actions/checkout@v3
#   with:
#     submodules: true