[build-system]
requires = ["setuptools>=42", "pybind11[global]", "cmake", "boost-cpp>=1.67.0"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-verbosity = 3
# Skip 32 bit architectures, musllinux, and i686
skip = ["*-win32", "*-musllinux_x86_64", "*_i686"]
before-build = "python -m pip install cmake"

[tool.cmake]
cmake-args = "-DBOOST_ROOT=$(python -c 'import boost_cpp; print(boost_cpp.include_paths()[0])')"


[tool.cibuildwheel.windows]
before-all = [
  "C:\\Miniconda\\condabin\\conda install -c conda-forge xsimd",
]

[tool.cibuildwheel.windows.environment]
INCLUDE="C:\\\\Miniconda\\\\Library\\\\include"

[tool.cibuildwheel.linux]
before-all = [
  "cd ~/",
  "git clone --branch 5.2.1 https://github.com/jemalloc/jemalloc.git",
  "cd jemalloc",
  "./autogen.sh --disable-cxx --with-jemalloc-prefix=local --with-install-suffix=local --disable-tls --disable-initial-exec-tls",
  "make",
  "make install_bin install_include install_lib",
  "cd ~/",
  "git clone --branch 7.6.0 https://github.com/xtensor-stack/xsimd.git",
  "cd xsimd",
  "mkdir build",
  "cd build",
  "cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..",
  "make install"
]