[build-system]
requires = ["setuptools>=42", "pybind11[global]"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-verbosity = 3
# Skip 32 bit architectures, musllinux, and i686
skip = ["*-win32", "*-musllinux_x86_64", "*_i686"]
