[build-system]
requires = ["setuptools>=42", "pybind11[global]"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-verbosity = 3

[tool.cibuildwheel.windows]
before-all = ["choco install eigen opencv"]
environment = { OpenCV_DIR="c:/tools/opencv/build" }
before-build = "pip install delvewheel"
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel} --add-path C:/tools/opencv/build/x64/vc15/bin"