name: build

on: [push]

jobs:
  # build_sdist:
  #   name: Build SDist
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Build SDist
  #     run: pipx run build --sdist

  #   - uses: actions/upload-artifact@v3
  #     with:
  #       path: dist/*.tar.gz
  
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Boost
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install libboost-all-dev
      - name: Install Boost
        if: matrix.os == 'windows-latest'
        run: choco install boost-msvc-14.2
      # - name: Build project
      #   run: make build
      - name: Run CMake
        run: |
          cmake -S . -B build 
        # -DBoost_INCLUDE_DIR=$BOOST_ROOT_1_74_0/include
        
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-* cp311-*
          CIBW_SKIP: "*-win32 *-musllinux_x86_64 *_i686"
          # CIBW_BEFORE_BUILD: python -m pip install cmake
          # CIBW_BEFORE_BUILD_LINUX: echo $BOOST_ROOT
          # CIBW_ENVIRONMENT_WINDOWS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
          # # CIBW_ENVIRONMENT_MACOS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
          # CIBW_ENVIRONMENT_LINUX: BOOST_ROOT=/boost
          # CIBW_ENVIRONMENT_PASS_LINUX: BOOST_ROOT

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload
    needs: [build_wheels] #, build_sdist
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPY_API_TOKEN }}