name: build

on: [push]

jobs:
  build_wheels:

    runs-on: ${{ matrix.os }}  #ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"] #["3.9", "3.10"]
        # exclude:
          # - os: macos-latest
            # python-version: ["3.9"]
          # - os: windows-latest
            # python-version: ["3.9"]
          # - os: ubuntu-latest
            # python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        
      - name: Install dependencies
        run: |
          python -m pip install cibuildwheel==2.11.2
          python -m pip install -U twine
          
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # env:  # Run the test suite after each build.
          # CIBW_TEST_REQUIRES: "pytest"
          # CIBW_TEST_COMMAND: pytest {package}/tests
      
      - name: Upload as build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl