name: build

on: [push]

jobs:
  # build_sdist:
  #   name: Build SDist
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Build SDist
  #     run: pipx run build --sdist

  #   - uses: actions/upload-artifact@v3
  #     with:
  #       path: dist/*.tar.gz
  
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
        
    - name: Install boost
      uses: MarkusJx/install-boost@v2.0.0
      id: install-boost
      with:
        boost_version: 1.72.0
        //platform_version: 2019
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/checkout@v3
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_BUILD: cp38-* cp39-* cp310-* cp311-*
        # BOOST_ROOT: '${{ steps.install-boost.outputs.BOOST_ROOT }}'
        # BOOST_ROOT_PIPELINE: '${{ steps.install-boost.outputs.BOOST_ROOT }}'
        # # Specify which Python versions to build wheels
        # # https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
        CIBW_SKIP: "*-win32 *-musllinux_x86_64 *_i686"
        # CIBW_BEFORE_BUILD: python -m pip install cmake
        # CIBW_BEFORE_BUILD_LINUX: echo $BOOST_ROOT
        # CIBW_BEFORE_ALL_LINUX: >
        #   yum install -y wget &&
        #   cd / &&  mkdir boost && cd boost &&
        #   wget --no-check-certificate 'https://sourceforge.net/projects/boost/files/boost/1.76.0/boost_1_76_0.tar.bz2' && 
        #   tar xf boost_1_76_0.tar.bz2 &&
        #   cd {package}
        # CIBW_TEST_COMMAND: python -m pytest --rootdir={package} {package}
        # CIBW_TEST_REQUIRES: pytest
        # CIBW_ENVIRONMENT_WINDOWS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
        # # CIBW_ENVIRONMENT_MACOS: BOOST_ROOT='${{ steps.install-boost.outputs.BOOST_ROOT }}'
        # CIBW_ENVIRONMENT_LINUX: BOOST_ROOT=/boost
        # CIBW_ENVIRONMENT_PASS_LINUX: BOOST_ROOT

    - uses: actions/upload-artifact@v3
      with:
        path: ./wheelhouse/*.whl

  upload_pypi:
    name: Upload
    needs: [build_wheels] #, build_sdist
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPY_API_TOKEN }}